on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            server: ${{ secrets.ftp_server }}
            username: ${{ secrets.ftp_username }}
            password: ${{ secrets.ftp_password }}
            local_path: './dist/*'
            remote_path: '/test'
            sftp_only: true
